<?php

return     [
        [
        'name' => 'La Taverna',
        'e-mail' => 'taverna@email.it',
        'password' =>'123456',
        'address' => 'Via Garibaldi, 13',
        'iva' => '60028970626',
        'logo_img' => 'img/restaurant/la-taverna.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
        'name' => 'Margherita',
        'e-mail' => 'margherita@email.it',
        'password' =>'123456' ,
        'address' => 'Via della Posta , 89',
        'iva' => '60028970626',
        'logo_img' => 'img/restaurant/margherita.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
        'name' => 'Il Chiostro',
        'e-mail' => 'ilchiostro@email.it',
        'password' =>'123456' ,
        'address' => 'Via del Municipio antico , 6',
        'iva' => '27178340389',
        'logo_img' => 'img/restaurant/il-chiostro.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
        'name' => 'Due Passi',
        'e-mail' => 'duepassi@email.it',
        'password' =>'123456' ,
        'address' => 'Via della Speranza , 66',
        'iva' => '68207150167',
        'logo_img' => 'img/restaurant/due-passi.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
        'name' => 'Itsu',
        'e-mail' => 'itsu@email.it',
        'password' =>'123456' ,
        'address' => 'Via Alfredo Renzi , 3',
        'iva' => '47769490088',
        'logo_img' => 'img/restaurant/itsu.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
        'name' => 'The Burger',
        'e-mail' => 'theburger@emial.it',
        'password' =>'123456' ,
        'address' => '	Via della Luna , 4',
        'iva' => '47769490088',
        'logo_img' => 'img/restaurant/the-burger.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
        'name' => 'Alla Griglia',
        'e-mail' => 'allagriglia@email.it',
        'password' =>'123456' ,
        'address' => 'Via del Domicilio , 3',
        'iva' => '47769490088',
        'logo_img' => 'img/restaurant/alla-griglia.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
        'name' => 'Mi Scusi',
        'e-mail' => 'miscusi@email.it',
        'password' =>'123456' ,
        'address' => 'Via XVII ottobre , 23',
        'iva' => '47769490088',
        'logo_img' => 'img/restaurant/mi-scusi.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
        'name' => 'Be Green',
        'e-mail' => 'begreen@email.it',
        'password' =>'123456', 
        'address' => 'Via Agostino , 23',
        'iva' => '47769490088',
        'logo_img' => 'img/restaurant/be-green.jpg',
        'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
        [
            'name' => 'Zero',
            'e-mail' => 'zero@email.it',
            'password' =>'123456', 
            'address' => 'Via Passatempo , 11',
            'iva' => '47769490088',
            'logo_img' => 'img/restaurant/zero.jpg',
            'banner_img' => 'img/restaurant/la-taverna.jpg',
        ],
    ];